### ISSUE TITLE
Slight impurity in `calcScore` function

### ISSUE THREAD

**Issue by RoryCombe** [knowthen/ramdatutorial#1]
Hi James, great series, I really enjoyed it. Was just wondering, and correct me if I'm wrong, but doesn't the `calcScore` function break the "Pure function rules" by relying externally on the constant `groupedByProp `? This would need to be handed in as an argument, no?

https://github.com/knowthen/ramdatutorial/blob/8132dece6d5754d3b6d6290a48fde08b23f7dc6e/index.js#L39-L54

**Comment by knowthen** [comment]
That's a good observation... In hindsight, I believe what you're suggesting is a better option.

I'll throw out another thought, for consideration.
If `groupedByProp` is truly a constant (I'm treating it as such, but JavaScript doesn't support it), then `calcScore` would be considered pure.

A simpler example:

```javascript
const PI = 3.14;

const radius = c => c / 2 * PI; 
```

So is `radius` pure?  It's depending on `PI`?  
If we just replaced `PI` in `radius` with `3.14`, then most people would quickly identify it as pure... but many people look at PI and think it's referencing something outside it's parameters, so it wouldn't seem to be pure.  

My answer... in a language that truly supports constants there's no difference between using `PI` or `3.14` in `radius`, so it's pure...
However we're in JavaScript so it's not as clear...  
Regardless, I think your observation is legit and a better option.

Best,
James
